[Protocol]
version = "849"

[Framework]
type = "default"

[WechatAPIServer]
host = "127.0.0.1"
port = 9011
mode = "release"
redis-host = "127.0.0.1"
redis-port = 6379
redis-password = ""
redis-db = 0

[Admin]
enabled = true
host = "0.0.0.0"
port = 9090
username = "admin"
password = "admin1234"
debug = true

[XYBot]
version = "v1.0.0"
ignore-protection = true
github-proxy = "https://ghfast.top/"
XYBotDB-url = "sqlite:///database/xybot.db"
msgDB-url = "sqlite+aiosqlite:///database/message.db"
keyvalDB-url = "sqlite+aiosqlite:///database/keyval.db"
admins = [
    "wxid_lnbsshdobq7y22",
]
disabled-plugins = [
    "ExamplePlugin",
    "TencentLke",
    "SiliconFlow",
    "Dify",
    "FastGPT",
]
timezone = "Asia/Shanghai"
auto-restart = false

[AutoRestart]
enabled = true
check-interval = 60
offline-threshold = 300
max-restart-attempts = 3
restart-cooldown = 1800
check-offline-trace = true
failure-count-threshold = 10
reset-threshold-multiplier = 3
ignore-mode = "None"
whitelist = [
    "wxid_uz9za1pqr3ea22",
    "wxid_l5im9jaxhr4412",
    "48369192388@chatroom",
]
blacklist = [
    "wxid_3",
    "wxid_4",
    "333@chatroom",
    "444@chatroom",
]

[Notification]
enabled = true
token = ""
channel = "wechat"
template = "html"
topic = ""
heartbeatThreshold = 3

[Notification.triggers]
offline = true
reconnect = true
restart = true
error = true

[Notification.templates]
offlineTitle = "警告：微信离线通知 - {time}"
offlineContent = "您的微信账号 <b>{wxid}</b> 已于 <span style=\"color:#ff4757;font-weight:bold;\">{time}</span> 离线，请尽快检查您的设备连接状态或重新登录。"
reconnectTitle = "微信重新连接通知 - {time}"
reconnectContent = "您的微信账号 <b>{wxid}</b> 已于 <span style=\"color:#2ed573;font-weight:bold;\">{time}</span> 重新连接。"
restartTitle = "系统重启通知 - {time}"
restartContent = "系统已于 <span style=\"color:#1e90ff;font-weight:bold;\">{time}</span> 重新启动。"

[Callback]
enabled = true
path = "python wx849_callback_sender.py"
delay = 0
mode = "all"

[Callback.filter]
types = [
    1,
    3,
    34,
    43,
    47,
    49,
    10000,
]
